function noaaResultsHandler(currentConditions) {
    var message = 'Current Conditions for Today: ';
    console.log(message + currentConditions.data.temperature[0]);
}

//--MAIN--
var noaaWeather = require('noaa-weather');
noaaWeather('ELK GROVE VILLAGE, IL').then(noaaResultsHandler);






/*{ operationalMode: 'Production',
  srsName: 'WGS 1984',
  creationDate: '2016-12-31T10:16:42-06:00',
  creationDateLocal: '31 Dec 09:51 am CST',
  productionCenter: 'Chicago, IL',
  credit: 'http://www.crh.noaa.gov/lot',
  moreInformation: 'http://weather.gov',
  location: 
   { region: 'crh',
     latitude: '42',
     longitude: '-88.02',
     elevation: '699',
     wfo: 'LOT',
     timezone: 'C|Y|6',
     areaDescription: 'Elk Grove Village IL',
     radar: 'KLOT',
     zone: 'ILZ014',
     county: 'ILC031',
     firezone: 'ILZ014',
     metar: 'KORD' },
  time: 
   { layoutKey: 'k-p12h-n13-1',
     startPeriodName: 
      [ 'Today',
        'Tonight',
        'New Year\'s Day',
        'Sunday Night',
        'Monday',
        'Monday Night',
        'Tuesday',
        'Tuesday Night',
        'Wednesday',
        'Wednesday Night',
        'Thursday',
        'Thursday Night',
        'Friday' ],
     startValidTime: 
      [ '2016-12-31T10:00:00-06:00',
        '2016-12-31T18:00:00-06:00',
        '2017-01-01T06:00:00-06:00',
        '2017-01-01T18:00:00-06:00',
        '2017-01-02T06:00:00-06:00',
        '2017-01-02T18:00:00-06:00',
        '2017-01-03T06:00:00-06:00',
        '2017-01-03T18:00:00-06:00',
        '2017-01-04T06:00:00-06:00',
        '2017-01-04T18:00:00-06:00',
        '2017-01-05T06:00:00-06:00',
        '2017-01-05T18:00:00-06:00',
        '2017-01-06T06:00:00-06:00' ],
     tempLabel: 
      [ 'High',
        'Low',
        'High',
        'Low',
        'High',
        'Low',
        'High',
        'Low',
        'High',
        'Low',
        'High',
        'Low',
        'High' ] },
  data: 
   { temperature: 
      [ '37',
        '20',
        '39',
        '31',
        '44',
        '39',
        '39',
        '15',
        '20',
        '9',
        '17',
        '8',
        '18' ],
     pop: 
      [ null,
        null,
        null,
        null,
        '70',
        '60',
        '20',
        null,
        null,
        null,
        null,
        null,
        null ],
     weather: 
      [ 'Cloudy',
        'Decreasing Clouds',
        'Increasing Clouds',
        'Mostly Cloudy',
        'Chance Rain then Rain Likely',
        'Rain Likely then Slight Chance Rain',
        'Mostly Cloudy then Slight Chance Rain/Snow',
        'Mostly Cloudy',
        'Mostly Sunny',
        'Partly Cloudy',
        'Partly Sunny',
        'Mostly Cloudy',
        'Partly Sunny' ],
     iconLink: 
      [ 'http://forecast.weather.gov/newimages/medium/ovc.png',
        'http://forecast.weather.gov/newimages/medium/nbkn.png',
        'http://forecast.weather.gov/newimages/medium/sct.png',
        'http://forecast.weather.gov/newimages/medium/nbkn.png',
        'http://forecast.weather.gov/DualImage.php?i=ra&j=ra&ip=40&jp=70',
        'http://forecast.weather.gov/DualImage.php?i=nra&j=nra&ip=60&jp=20',
        'http://forecast.weather.gov/DualImage.php?i=bkn&j=ra_sn&jp=20',
        'http://forecast.weather.gov/newimages/medium/nbkn.png',
        'http://forecast.weather.gov/newimages/medium/sct.png',
        'http://forecast.weather.gov/newimages/medium/nsct.png',
        'http://forecast.weather.gov/newimages/medium/bkn.png',
        'http://forecast.weather.gov/newimages/medium/nbkn.png',
        'http://forecast.weather.gov/newimages/medium/bkn.png' ],
     hazard: [],
     hazardUrl: [],
     text: 
      [ 'Cloudy, with a temperature falling to around 31 by 5pm. West wind around 15 mph, with gusts as high as 25 mph. ',
        'Mostly cloudy, then gradually becoming mostly clear, with a low around 20. West northwest wind 5 to 10 mph becoming south southwest after midnight. Winds could gust as high as 20 mph. ',
        'Increasing clouds, with a high near 39. South southwest wind around 5 mph becoming southeast in the afternoon. ',
        'Mostly cloudy, with a low around 31. East southeast wind around 5 mph. ',
        'Rain likely, mainly after noon.  Cloudy, with a high near 44. Southeast wind 5 to 10 mph.  Chance of precipitation is 70%.',
        'Rain likely, mainly before midnight.  Cloudy, with a low around 39. Chance of precipitation is 60%.',
        'A slight chance of rain and snow after noon.  Mostly cloudy, with a high near 39. Chance of precipitation is 20%.',
        'Mostly cloudy, with a low around 15.',
        'Mostly sunny, with a high near 20.',
        'Partly cloudy, with a low around 9.',
        'Partly sunny, with a high near 17.',
        'Mostly cloudy, with a low around 8.',
        'Partly sunny, with a high near 18.' ] },
  currentobservation: 
   { id: 'KORD',
     name: 'Chicago, Chicago-O\'Hare International Airport',
     elev: '666',
     latitude: '41.98',
     longitude: '-87.9',
     Date: '31 Dec 09:51 am CST',
     Temp: '40',
     Dewp: '24',
     Relh: '53',
     Winds: '17',
     Windd: '300',
     Gust: '25',
     Weather: 'Mostly Cloudy',
     Weatherimage: 'bkn.png',
     Visibility: '10.00',
     Altimeter: '1002.7',
     SLP: '29.60',
     timezone: 'CST',
     state: 'IL',
     WindChill: '31' } 
}*/